apiVersion: "v1"
kind: Template
objects:
- apiVersion: "v1"
  kind: "ImageStream"
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
    namespace: ${NAMESPACE}

- apiVersion: "v1"
  kind: "BuildConfig"
  metadata:
    name: "${APPLICATION_NAME}-pipeline"
    labels:
      application: ${APPLICATION_NAME}
  spec:
    source:
      git:
        uri: ${GIT_REPO}
        ref: main
      sourceSecret:
        name: ${SSH_KEY_NAME}
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: Jenkinsfile
        env:
          - name: "BUILD_LOGLEVEL"
            value: "5"
      type: JenkinsPipeline
- apiVersion: v1
  kind: "BuildConfig"
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
    namespace: "${NAMESPACE}"
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APPLICATION_NAME}:latest
    source:
      binary: {}
      type: Binary
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: "${IMAGE_STREAM_TAG_NAME}"
          namespace: "${IMAGE_STREAM_NAMESPACE}"
        env:
          - name: "BUILD_LOGLEVEL"
            value: "5"
      type: Source
parameters:
- description: Application Name
  displayName: Application Name
  name: APPLICATION_NAME
  required: true
  value: angular-jenkins
- description: Namespace
  displayName: Namespace
  name: NAMESPACE
  required: true
  value: 
- description: Git repo
  displayName: Git repo
  name: GIT_REPO
  required: false
  value: https://github.com/sholly/angular-openshift.git
- description: Namespace in which the ImageStreams for Red Hat Middleware images are
    installed. These ImageStreams are normally installed in the openshift namespace.
    You should only need to modify this if you've installed the ImageStreams in a
    different namespace/project.
  name: IMAGE_STREAM_NAMESPACE
  required: true
  value: openshift
- description: Image stream tag for the image you'd like to use to build the application
  name: IMAGE_STREAM_TAG_NAME
  required: true
  value: nginx:1.18-ubi8
- description: Quay build tag
  name: BUILD_TAG
  required: true
  value: devrc
